## Load Mathdial Datatset

In [1]:
from datasets import load_dataset
 
# Login using e.g. `huggingface-cli login` to access this dataset
ds = load_dataset("eth-nlped/mathdial")

c:\Users\PC\OneDrive - ESPRIT\Bureau\RAG\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
ds

DatasetDict({
    train: Dataset({
        features: ['qid', 'scenario', 'question', 'ground_truth', 'student_incorrect_solution', 'student_profile', 'teacher_described_confusion', 'self-correctness', 'self-typical-confusion', 'self-typical-interactions', 'conversation'],
        num_rows: 2262
    })
    test: Dataset({
        features: ['qid', 'scenario', 'question', 'ground_truth', 'student_incorrect_solution', 'student_profile', 'teacher_described_confusion', 'self-correctness', 'self-typical-confusion', 'self-typical-interactions', 'conversation'],
        num_rows: 599
    })
})

In [3]:
ds.shape

{'train': (2262, 11), 'test': (599, 11)}

In [4]:
df = ds["train"].to_pandas()

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2262 entries, 0 to 2261
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   qid                          2262 non-null   int64
 1   scenario                     2262 non-null   int64
 2   question                     2262 non-null   str
 3   ground_truth                 2262 non-null   str
 4   student_incorrect_solution   2262 non-null   str
 5   student_profile              2262 non-null   str
 6   teacher_described_confusion  2253 non-null   str
 7   self-correctness             2253 non-null   str
 8   self-typical-confusion       2253 non-null   float64
 9   self-typical-interactions    2253 non-null   float64
 10  conversation                 2262 non-null   str
dtypes: float64(2), int64(2), str(7)
memory usage: 6.4 MB

In [6]:
df.head()

,qid,scenario,question,ground_truth,student_incorrect_solution,student_profile,teacher_described_confusion,self-correctness,self-typical-confusion,self-typical-interactions,conversation
0,5000012,1,Nancy is filling an aquarium for her fish. She...,First calculate the volume of the aquarium by ...,The aquarium has a volume of 4 x 6 x 3 = 72 cu...,Steven is a 7th grade student. He has difficul...,He added a step after completing the problem.,Yes,3.0,3.0,"Teacher: (probing)Steven, If you had 4 of some..."
1,5000084,2,John is very unfit and decides to work up to d...,He needs to do 15*3=45 progressions\nThat will...,"To get to 15 reps, John will take 15 - 1 = 14 ...",Stephanie is a 7th grade student. She has diff...,She became fixated on a wrong calculation and ...,No,2.0,2.0,"Teacher: (probing)Stephanie, How many days wil..."
2,5000982,3,James has 20 pairs of red socks and half as ma...,He has 20/2=10 black socks\nSo he has 20+10=30...,James has 20/2 = 10 pairs of black socks.\nJam...,DeAndre is a 7th grade student. He has problem...,He was technically correct.,Yes,5.0,5.0,"Teacher: (probing)DeAndre, you successfully an..."
3,5000274,4,Jason drives past 3 convenience stores on his ...,First find the additional distance between the...,The distance between the second store and thir...,Winnie is a 7th grade student. She struggle to...,He understood it when it was broken down step ...,Yes,3.0,3.0,Teacher: (probing)What is the distance between...
4,5000797,5,Wanda walks her daughter .5 miles to school in...,She walks .5 miles to school and back 4 times ...,"Every day, Wanda walks a total of 0.5 + 0.5 = ...",Cody is a 7th grade student. He has problem wi...,He forgot she walked twice each day!,Yes,3.0,3.0,"Teacher: (probing)Cody, How far doe Wanda walk..."

In [7]:
df.columns

Index(['qid', 'scenario', 'question', 'ground_truth',
       'student_incorrect_solution', 'student_profile',
       'teacher_described_confusion', 'self-correctness',
       'self-typical-confusion', 'self-typical-interactions', 'conversation'],
      dtype='str')

## <font color='blue' ><h2>
Data Cleaning </p><h2>

In [8]:
df.isnull().values.any()

np.True_

In [9]:
df.isnull().sum()

qid                            0
scenario                       0
question                       0
ground_truth                   0
student_incorrect_solution     0
student_profile                0
teacher_described_confusion    9
self-correctness               9
self-typical-confusion         9
self-typical-interactions      9
conversation                   0
dtype: int64

## We have 9 rows with self-typical-interactions, self-typical-confusion, self-correctness and teacher_described_confusion = NaN

In [10]:
df[df.isnull().any(axis=1)]

,qid,scenario,question,ground_truth,student_incorrect_solution,student_profile,teacher_described_confusion,self-correctness,self-typical-confusion,self-typical-interactions,conversation
224,5000338,5,In one of the building blocks at Oakland High ...,Each ml of ink costs 50 cents so 20 ml costs 2...,There are 5 classes and each class uses 2 whit...,Lakisha is a 7th grade student. She has proble...,NaN,NaN,NaN,NaN,Teacher: (generic)Show me your workings|EOM|St...
238,5000961,4,"For his birthday, Geoffrey received clothes an...",Let’s calculate the total price of video games...,Geoffrey received 20 + 25 + 30 = 75 euros.\nWi...,Cody is a 7th grade student. He has difficulty...,NaN,NaN,NaN,NaN,"Teacher: (generic)Hello Cody, please you can t..."
369,5000597,2,Carmen burns a candle for 1 hour every night. ...,Burning a candle for 1 hour lasts her 8 nights...,Carmen uses 1 x 8 = 8 hours of candle for 1 ca...,Heidi is a 7th grade student. She has difficul...,NaN,NaN,NaN,NaN,Teacher: (probing)We know that 1 candle last 8...
514,5000449,1,The base of a hill located beside a river is 3...,300m is a quarter of the distance from the riv...,Let's start by setting up an equation to repre...,Jia is a 7th grade student. She has difficulty...,NaN,NaN,NaN,NaN,Teacher: (telling)walk me thorugh your solutio...
878,5000374,2,Nissa is calculating a jail sentence for a man...,First find how many years the base sentence wi...,"The base sentence for stealing $40,000 worth o...",Jordy is a 7th grade student. He has problem w...,NaN,NaN,NaN,NaN,"Teacher: (generic)Hello, Jordy. Please walk me..."
1045,5000820,4,Martha has 20 apples. She decided to split the...,Martha gave James 5 + 2 = 7 apples.\nSo Martha...,"After giving away 5 apples to Jane, Martha is ...",Ayisha is a 7th grade student. She has problem...,NaN,NaN,NaN,NaN,"Teacher: (generic)Hi Ayisha, please talk me th..."
1287,5001080,2,Emberly takes her mornings walks every day. If...,"In March, she walked for 31-4 = 27 days.\nIf s...",Emberly walks for 1 hour every day covering 4 ...,Jordy is a 7th grade student. He struggle to p...,NaN,NaN,NaN,NaN,"Teacher: (generic)Hi Jordy, your answer is inc..."
1769,5000007,1,Artemis is making tea for a party. She knows h...,She is making 72 ounces of water because 12 x ...,Each person will drink 6/8 = 0.75 cups of tea....,Ayisha is a 7th grade student. She has problem...,NaN,NaN,NaN,NaN,"Teacher: (generic)Hi, could you please walk me..."
2106,5001103,2,"Hillary always buys the Wednesday, Thursday an...","She buys Wednesday, Thursday and Friday's pape...","Hillary buys the Wednesday, Thursday and Frida...",Rishi is a 7th grade student. He struggle to p...,NaN,NaN,NaN,NaN,"Teacher: (generic)Hi Rishi, could you please w..."



Agent 1 simulates the student, therefore **teacher_described_confusion** is useful to guide the LLM to produce realistic mistakes.

The training dataset contains ~2.26k samples, and only 9 rows have missing values in pedagogical fields (`teacher_described_confusion`, `self-correctness`, `self-typical-confusion`, `self-typical-interactions`). Since this represents <0.5% of the data, these rows are dropped to ensure consistent supervision signals.

Additionally, the following columns are removed because they are not required for the RAG pipeline:

- `scenario`
- `self-typical-interactions`
- `self-typical-confusion`
- `self-correctness`

In [11]:
cols_required = [
    "teacher_described_confusion",
    "self-correctness",
    "self-typical-confusion",
    "self-typical-interactions"
]

df = df.dropna(subset=cols_required).reset_index(drop=True)

In [12]:
df.isnull().sum()

qid                            0
scenario                       0
question                       0
ground_truth                   0
student_incorrect_solution     0
student_profile                0
teacher_described_confusion    0
self-correctness               0
self-typical-confusion         0
self-typical-interactions      0
conversation                   0
dtype: int64

In [13]:
cols_to_remove = [
    "scenario",
    "self-typical-interactions",
    "self-typical-confusion",
    "self-correctness"
]

df = df.drop(columns=cols_to_remove)

df.columns

Index(['qid', 'question', 'ground_truth', 'student_incorrect_solution',
       'student_profile', 'teacher_described_confusion', 'conversation'],
      dtype='str')

In [14]:
df.shape

(2253, 7)

# No Duplicates

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df.drop_duplicates()
df.shape

(2253, 7)

### Keep only different questions/student_incorrect_solution for the project context

In [17]:
# keep only one row per qid (remove duplicates)
df = df.drop_duplicates(subset="qid")

# optional: reset index
df = df.reset_index(drop=True)

In [18]:
df.shape

(1034, 7)

## Text preprocessing

No classical NLP preprocessing is applied, such as:

- removing stop words
- stemming
- lemmatization
- manual tokenization
- lowercasing everything
- removing punctuation

Since the RAG pipeline relies on semantic embeddings, the model already handles tokenization and preserves meaning. Modifying the text could reduce important context, especially in tutoring dialogues.

Therefore, the text is kept in its original form.

# Chunking

### Chunking strategy for Agent 1

For Agent 1, retrieval is based only on the question. At the beginning of the interaction, no incorrect student solution exists yet, since Agent 1 must first generate a flawed response.

Therefore, each chunk is indexed using the question only, while fields such as student_incorrect_solution and teacher_described_confusion are kept as metadata and used after retrieval to guide the generation of a realistic mistake.

In [19]:
chunks = []

for _, row in df.iterrows():
    
    chunk = {
        "text": row["question"],

        "metadata": {
            "qid": row["qid"],
            "student_incorrect_solution": row["student_incorrect_solution"],
            "teacher_described_confusion": row["teacher_described_confusion"],
            "ground_truth": row["ground_truth"],
           
        }
    }
    
    chunks.append(chunk)

len(chunks)

1034

In [20]:
chunks[0]

{'text': "Nancy is filling an aquarium for her fish. She fills it halfway and goes to answer the door. While she's gone, her cat knocks the aquarium over and spills half the water in it. Then Nancy comes back and triples the amount of water in the aquarium. If the aquarium is 4 feet long, 6 feet wide, and 3 feet high, how many cubic feet of water are in the aquarium?",
 'metadata': {'qid': 5000012,
  'student_incorrect_solution': 'The aquarium has a volume of 4 x 6 x 3 = 72 cubic feet.\nWhen Nancy fills it halfway, she fills it with 72/2 = 36 cubic feet of water.\nWhen the cat spills half of that, there are 36/2 = 18 cubic feet of water left.\nWhen Nancy triples that amount, she adds 18 x 3 = 54 cubic feet of water.\nThe aquarium now has 18 + 54 = 72 cubic feet of water.\n 72',
  'teacher_described_confusion': 'He added a step after completing the problem.',
  'ground_truth': "First calculate the volume of the aquarium by multiplying its length, width and height: 4 ft * 6 ft * 3 ft = 72 cubic ft\nThen figure out what proportion of the aquarium is full after the cat knocks it over: 1/2 * 1/2 = 1/4\nThen figure out what proportion of the aquarium is full after Nancy refills it: 3 * 1/4 = 3/4\nNow multiply the proportion of the aquarium that's full by the aquarium's volume to find out how much water is in it: 72 cubic ft * 3/4 = 54 cubic ft\n 54"}}

# Embedding

### Models selection

We use open-source models for both embeddings and generation to keep the pipeline fully local and reproducible.

For embeddings, we use all-MiniLM-L6-v2, a lightweight model that provides efficient semantic similarity while requiring low computational resources. Since the questions are relatively short (max 148 words), the model’s context capacity is sufficient while maintaining fast inference.

We use Qwen2.5-Instruct as the generator (used later for Agent 1 and Agent 2) because instruction-tuned models are optimized to follow prompts and produce structured, step-by-step explanations, which is well suited for RAG and tutoring tasks.

In [21]:
df["question_length_words"] = df["question"].apply(lambda x: len(x.split()))

df["question_length_words"].describe()

count    1034.000000
mean       50.034816
std        17.778097
min        15.000000
25%        38.000000
50%        47.000000
75%        57.000000
max       148.000000
Name: question_length_words, dtype: float64

In [22]:
df["question"].apply(lambda x: len(x.split())).max()

np.int64(148)

In [23]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 5007.34it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [24]:
texts = [chunk["text"] for chunk in chunks]

embeddings = model.encode(
    texts,
    show_progress_bar=True,
    normalize_embeddings=True
)

len(embeddings), len(embeddings[0])

Batches: 100%|██████████| 33/33 [00:04<00:00,  6.80it/s]

(1034, 384)

In [25]:
embeddings

array([[ 0.07655008,  0.07701679,  0.02975876, ...,  0.12262737,
         0.09548932,  0.0384492 ],
       [-0.0053869 , -0.00894548, -0.00885906, ..., -0.03457317,
         0.0025234 ,  0.04274339],
       [ 0.03213458,  0.05919671, -0.01603932, ..., -0.0021541 ,
        -0.06267177, -0.00739999],
       ...,
       [ 0.0938304 ,  0.02103353,  0.03866859, ...,  0.07906018,
         0.02243602, -0.02017422],
       [ 0.04937107,  0.03989574,  0.02769   , ...,  0.00020328,
        -0.04766673, -0.0071512 ],
       [ 0.03629148,  0.08786575, -0.00128125, ...,  0.05533825,
        -0.0164799 ,  0.01972748]], shape=(1034, 384), dtype=float32)

## ChromaDB

In [26]:
import chromadb

# create database (simple version)
client = chromadb.Client()

# create collection
collection = client.create_collection(name="mathdial", configuration={"hnsw": {"space": "cosine"}})

# prepare data
documents = [chunk["text"] for chunk in chunks]
metadatas = [chunk["metadata"] for chunk in chunks]
ids = [str(i) for i in range(len(chunks))]

# store embeddings
collection.add(
    documents=documents,
    embeddings=embeddings,
    metadatas=metadatas,
    ids=ids
)

In [27]:
# print(client.list_collections()) # client.delete_collection("Mathdial")

In [28]:
collection.count()

1034

Cosine similarity is used as the distance metric for retrieval.

In [29]:
print(collection.configuration)

{'hnsw': {'space': 'cosine', 'ef_construction': 100, 'ef_search': 100, 'max_neighbors': 16, 'resize_factor': 1.2, 'sync_threshold': 1000}, 'spann': None, 'embedding_function': <chromadb.api.types.DefaultEmbeddingFunction object at 0x0000022C77DD7330>}

In [30]:
def retrieve_examples(query, collection, top_k=5):
    
    # convert query into embedding
    query_embedding = model.encode(query).tolist()
    
    # search similar questions
    results = collection.query(
        query_embeddings=[query_embedding],
        
        n_results=top_k
    )
    
    retrieved_questions = results["documents"][0]
    retrieved_metadata = results["metadatas"][0]
    
    examples = []
    
    for i in range(len(retrieved_questions)):
        
        example = {
            "question": retrieved_questions[i],
            "qid": retrieved_metadata[i]["qid"],
            "student_incorrect_solution": retrieved_metadata[i]["student_incorrect_solution"],
            "teacher_described_confusion": retrieved_metadata[i]["teacher_described_confusion"],
            "ground_truth": retrieved_metadata[i]["ground_truth"],
            
        }
        
        examples.append(example)
    
    return examples

In [31]:
query = "There are 5 apples and 10 carrots in the basket."

example = retrieve_examples(query, collection, top_k=2)

example

[{'question': 'Tania has five baskets containing a total of 58 fruits. There are 18 mangoes in one basket, 10 pears in another, 12 pawpaws in another and the last 2 contain the same number of kiwi and lemon respectively, how many lemons are there?',
  'qid': 5000653,
  'student_incorrect_solution': "The first three baskets contain a total of 18+10+12 = 40 fruits.\nThe last two baskets contain a total of 58-40 = 18 fruits.\nLet's assume there are x lemons in one of the baskets.\nThen the other basket contains x kiwi fruits.\nSo, we have x + x = 2x fruits in the last basket.\nThus, x + 2x = 18, which gives us 3x = 18.\nTherefore, x = 6.\nThus, there are 6 lemons in one of the baskets.\n 6",
  'teacher_described_confusion': 'The student was getting confused between the amount of baskets and diving by 3 not 2.',
  'ground_truth': 'The sum of mangoes, pears and pawpaws is 18+10+12 = 40\nThe total number of fruits is 58 so the last two baskets contain 58-40 = 18 fruits\nEach of the last two baskets contains an equal amount of fruits which is 18/2 = 9 fruits\n 9'},
 {'question': 'Tanya went to the grocery store to buy some fruit.  She bought 6 pears, 4 Granny Smith apples, 2 pineapples, and a small basket of plums, which were all placed in a single paper bag.  Unfortunately, the bag that the fruit had been placed in had developed a hole.  Therefore, as Tanya walked home, half of the fruit fell out of the bag.  When she later counted the fruit left in the bag, there were only 9 pieces remaining.  How many plums did she buy?',
  'qid': 5000071,
  'student_incorrect_solution': "Let's first find out how many pieces of fruit Tanya originally had in the bag before half fell out.\nTanya bought 6 pears + 4 apples + 2 pineapples + x plums = 10 + x total pieces of fruit\nHalf of the fruit fell out, so Tanya was left with (10 + x)/2 = 9 pieces of fruit.\nMultiplying both sides by 2 gives us 10 + x = 18.\nSubtracting 10 from both sides gives us x = 8.\nTherefore, Tanya bought 8 plums.\n 8",
  'teacher_described_confusion': 'Did not understand the question',
  'ground_truth': 'If half of the fruit equals 9 pieces, then Tanya bought 2*9=18 pieces of fruit.\nThus, Tanya bought 18-6-4-2=6 plums.\n 6'}]

In [32]:
query = "Sarah has 24 eggs. She gives 1/3 of them to her friend. How many eggs does Sarah have left?"

example = retrieve_examples(query, collection, top_k=2)

example

[{'question': 'Samantha bought a crate of 30 eggs for $5. If she decides to sell each egg for 20 cents, how many eggs will she have left by the time she recovers her capital from the sales?',
  'qid': 5000701,
  'student_incorrect_solution': 'Samantha spent $5 on 30 eggs, so each egg cost 5/30 = $0.16666666667 (rounded to 2 decimal places).\nTo recover her capital, Samantha needs to sell 30 x $0.20 = $6 worth of eggs.\nTo find out how many eggs she needs to sell to reach $6, we divide $6 by $0.20 per egg, which is 6/0.20 = 30 eggs.\nTherefore, Samantha will have no eggs left by the time she recovers her capital from the sales.\n 0',
  'teacher_described_confusion': 'Confuses the total amount which can be made with the capital.',
  'ground_truth': 'There are 100 cents in each $1 so $5 gives 5*100 cents = 500 cents\nTo recover her capital of 500 cents from a selling price of 20 cents per egg she has to sell 500/20 = 25 eggs\nThere were 30 eggs in the crate to start with so she will have 30-25 = 5 eggs left\n 5'},
 {'question': 'Linda was gathering eggs from her chicken coops. When she was done, she had three times as many white eggs as brown eggs. On her way back to the house, she stumbled, dropping her egg basket. Upon inspecting the damage, she found that all 5 of the brown eggs survived, but now she only had a dozen eggs left. How many eggs did Linda break?',
  'qid': 5000618,
  'student_incorrect_solution': "If Linda had a dozen eggs left after the accident, she originally had 12 + 5 = 17 eggs.\nLet's say Linda had b brown eggs. Then she had 3b white eggs. \nSo, the total number of eggs Linda had was b + 3b = 4b.\nWe know that 4b = 17, so b = 4.25 (not a whole number, so the problem may not be realistic).\nSince Linda only had 5 brown eggs left, she must have broken 4 brown eggs. \n 4",
  'teacher_described_confusion': 'The student added the 5 brown eggs twice to the number of surviving eggs. Also, some arithmetic issues, the student seems to believe that 15-7=7, when it is actually 8.',
  'ground_truth': 'Linda has 12 eggs left, 5 of which are brown, so 12 - 5 = 7 are white.\nLinda originally had 3 times as many white eggs as brown eggs, or 3 * 5 = 15 white eggs.\nSo Linda broke 15 - 7 = 8 white eggs.\n 8'}]

In [33]:
# /n Problem Python
print(example[1]["ground_truth"])

Linda has 12 eggs left, 5 of which are brown, so 12 - 5 = 7 are white.
Linda originally had 3 times as many white eggs as brown eggs, or 3 * 5 = 15 white eggs.
So Linda broke 15 - 7 = 8 white eggs.
 8

## Generator (Agent 1)

In [34]:
import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

True
NVIDIA GeForce GTX 1050

In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM
# Pytorch software library used to run neural networks.
import torch

model_name = "Qwen/Qwen2.5-1.5B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    # 1.5B parameters × 2 bytes ≈ 3 GB VRAM
    torch_dtype=torch.float16,
    # automatically uses GPU if available, otherwise CPU
    device_map="cuda",
    
    
)

OutOfMemoryError: CUDA out of memory. Tried to allocate 2.80 GiB. GPU 0 has a total capacity of 4.00 GiB of which 0 bytes is free. Of the allocated memory 2.88 GiB is allocated by PyTorch, and 19.47 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

In [ ]:
prompt = "Nancy is filling an aquarium for her fish. She fills it halfway and goes to answer the door. While she's gone, her cat knocks the aquarium over and spills half the water in it. Then Nancy comes back and triples the amount of water in the aquarium. If the aquarium is 4 feet long, 6 feet wide, and 3 feet high, how many cubic feet of water are in the aquarium?"
messages = [

    {"role": "system", "content": """You are a helpful math tutor for 7th grade students.
     Write all mathematical expressions using LaTeX.
     Always enclose any display-style mathematical calculation or equation using double dollar signs, like this: $$...$$. 
     
     
    Respond in JSON format with:
    {{
        
    "is_math_problem": true/false,
    "explanation": "short explanation"

    }}
    
    return ONLY valid JSON, no additional text or markdown formatting"""},
    {"role": "user", "content": prompt}
]
text = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
)
model_inputs = tokenizer([text], return_tensors="pt").to(model.device)

generated_ids = model.generate(
    **model_inputs,
    max_new_tokens=200
)
generated_ids = [
    output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)
]

response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]

print(response)

```json
{
    "is_math_problem": true,
    "explanation": "To find out how much water is in the aquarium after all these events, we need to follow each step carefully."
}
```