In [ ]:
!pip install --no-cache-dir -q pandas

In [ ]:
!pip install --no-cache-dir -q huggingface_hub

In [ ]:
!pip install --no-cache-dir -q datasets

In [ ]:
!pip install --no-cache-dir -q sentence-transformers

In [ ]:
!pip install --no-cache-dir -q transformers

In [ ]:
!pip install --no-cache-dir -q accelerate

In [ ]:
!pip install --no-cache-dir -q chromadb

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.0/52.0 kB 5.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.6/21.6 MB 347.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.2/278.2 kB 381.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 325.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.2/17.2 MB 235.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.1/72.1 kB 270.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.0/142.0 kB 314.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.7/68.7 kB 245.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 231.6/231.6 kB 357.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.6/71.6 kB 304.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 290.0 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opentelemetry-exporter-gcp-logging 1.11.0a0 requires opentelemetry-sdk<1.39.0,>=1.35.0, but you have opentelemetry-sdk 1.40.0 which is incompatible.
google-adk 1.27.1 requires opentelemetry-api<1.39.0,>=1.36.0, but you have opentelemetry-api 1.40.0 which is incompatible.
google-adk 1.27.1 requires opentelemetry-sdk<1.39.0,>=1.36.0, but you have opentelemetry-sdk 1.40.0 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-exporter-otlp-proto-common==1.38.0, but you have opentelemetry-exporter-otlp-proto-common 1.40.0 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-proto==1.38.0, but you have opentelemetry-proto 1.40.0 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-sdk~=1.38.0, but you have opentelemetry-sdk 1.40.0 which is incompatible.

In [ ]:
from huggingface_hub import notebook_login
notebook_login()

## Load Mathdial Datatset

In [ ]:
from datasets import load_dataset

# Login using e.g. `huggingface-cli login` to access this dataset
ds = load_dataset("eth-nlped/mathdial")

README.md: 0.00B [00:00, ?B/s]

train.jsonl: 0.00B [00:00, ?B/s]

test.jsonl: 0.00B [00:00, ?B/s]

Generating train split:   0%|          | 0/2262 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/599 [00:00<?, ? examples/s]

In [ ]:
ds

DatasetDict({
    train: Dataset({
        features: ['qid', 'scenario', 'question', 'ground_truth', 'student_incorrect_solution', 'student_profile', 'teacher_described_confusion', 'self-correctness', 'self-typical-confusion', 'self-typical-interactions', 'conversation'],
        num_rows: 2262
    })
    test: Dataset({
        features: ['qid', 'scenario', 'question', 'ground_truth', 'student_incorrect_solution', 'student_profile', 'teacher_described_confusion', 'self-correctness', 'self-typical-confusion', 'self-typical-interactions', 'conversation'],
        num_rows: 599
    })
})

In [ ]:
ds.shape

{'train': (2262, 11), 'test': (599, 11)}

In [ ]:
df = ds["train"].to_pandas()

In [ ]:
df_test = ds["test"].to_pandas()

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2262 entries, 0 to 2261
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   qid                          2262 non-null   int64
 1   scenario                     2262 non-null   int64
 2   question                     2262 non-null   object
 3   ground_truth                 2262 non-null   object
 4   student_incorrect_solution   2262 non-null   object
 5   student_profile              2262 non-null   object
 6   teacher_described_confusion  2253 non-null   object
 7   self-correctness             2253 non-null   object
 8   self-typical-confusion       2253 non-null   float64
 9   self-typical-interactions    2253 non-null   float64
 10  conversation                 2262 non-null   object
dtypes: float64(2), int64(2), object(7)
memory usage: 194.5+ KB

In [ ]:
df.head()

,qid,scenario,question,ground_truth,student_incorrect_solution,student_profile,teacher_described_confusion,self-correctness,self-typical-confusion,self-typical-interactions,conversation
0,5000012,1,Nancy is filling an aquarium for her fish. She...,First calculate the volume of the aquarium by ...,The aquarium has a volume of 4 x 6 x 3 = 72 cu...,Steven is a 7th grade student. He has difficul...,He added a step after completing the problem.,Yes,3.0,3.0,"Teacher: (probing)Steven, If you had 4 of some..."
1,5000084,2,John is very unfit and decides to work up to d...,He needs to do 15*3=45 progressions\nThat will...,"To get to 15 reps, John will take 15 - 1 = 14 ...",Stephanie is a 7th grade student. She has diff...,She became fixated on a wrong calculation and ...,No,2.0,2.0,"Teacher: (probing)Stephanie, How many days wil..."
2,5000982,3,James has 20 pairs of red socks and half as ma...,He has 20/2=10 black socks\nSo he has 20+10=30...,James has 20/2 = 10 pairs of black socks.\nJam...,DeAndre is a 7th grade student. He has problem...,He was technically correct.,Yes,5.0,5.0,"Teacher: (probing)DeAndre, you successfully an..."
3,5000274,4,Jason drives past 3 convenience stores on his ...,First find the additional distance between the...,The distance between the second store and thir...,Winnie is a 7th grade student. She struggle to...,He understood it when it was broken down step ...,Yes,3.0,3.0,Teacher: (probing)What is the distance between...
4,5000797,5,Wanda walks her daughter .5 miles to school in...,She walks .5 miles to school and back 4 times ...,"Every day, Wanda walks a total of 0.5 + 0.5 = ...",Cody is a 7th grade student. He has problem wi...,He forgot she walked twice each day!,Yes,3.0,3.0,"Teacher: (probing)Cody, How far doe Wanda walk..."

In [ ]:
df.columns

Index(['qid', 'scenario', 'question', 'ground_truth',
       'student_incorrect_solution', 'student_profile',
       'teacher_described_confusion', 'self-correctness',
       'self-typical-confusion', 'self-typical-interactions', 'conversation'],
      dtype='object')

## <font color='blue' ><h2>
Data Cleaning </p><h2>

In [ ]:
df.isnull().values.any()

np.True_

In [ ]:
df.isnull().sum()

qid                            0
scenario                       0
question                       0
ground_truth                   0
student_incorrect_solution     0
student_profile                0
teacher_described_confusion    9
self-correctness               9
self-typical-confusion         9
self-typical-interactions      9
conversation                   0
dtype: int64

## We have 9 rows with self-typical-interactions, self-typical-confusion, self-correctness and teacher_described_confusion = NaN

In [ ]:
df[df.isnull().any(axis=1)]

,qid,scenario,question,ground_truth,student_incorrect_solution,student_profile,teacher_described_confusion,self-correctness,self-typical-confusion,self-typical-interactions,conversation
224,5000338,5,In one of the building blocks at Oakland High ...,Each ml of ink costs 50 cents so 20 ml costs 2...,There are 5 classes and each class uses 2 whit...,Lakisha is a 7th grade student. She has proble...,None,None,NaN,NaN,Teacher: (generic)Show me your workings|EOM|St...
238,5000961,4,"For his birthday, Geoffrey received clothes an...",Let’s calculate the total price of video games...,Geoffrey received 20 + 25 + 30 = 75 euros.\nWi...,Cody is a 7th grade student. He has difficulty...,None,None,NaN,NaN,"Teacher: (generic)Hello Cody, please you can t..."
369,5000597,2,Carmen burns a candle for 1 hour every night. ...,Burning a candle for 1 hour lasts her 8 nights...,Carmen uses 1 x 8 = 8 hours of candle for 1 ca...,Heidi is a 7th grade student. She has difficul...,None,None,NaN,NaN,Teacher: (probing)We know that 1 candle last 8...
514,5000449,1,The base of a hill located beside a river is 3...,300m is a quarter of the distance from the riv...,Let's start by setting up an equation to repre...,Jia is a 7th grade student. She has difficulty...,None,None,NaN,NaN,Teacher: (telling)walk me thorugh your solutio...
878,5000374,2,Nissa is calculating a jail sentence for a man...,First find how many years the base sentence wi...,"The base sentence for stealing $40,000 worth o...",Jordy is a 7th grade student. He has problem w...,None,None,NaN,NaN,"Teacher: (generic)Hello, Jordy. Please walk me..."
1045,5000820,4,Martha has 20 apples. She decided to split the...,Martha gave James 5 + 2 = 7 apples.\nSo Martha...,"After giving away 5 apples to Jane, Martha is ...",Ayisha is a 7th grade student. She has problem...,None,None,NaN,NaN,"Teacher: (generic)Hi Ayisha, please talk me th..."
1287,5001080,2,Emberly takes her mornings walks every day. If...,"In March, she walked for 31-4 = 27 days.\nIf s...",Emberly walks for 1 hour every day covering 4 ...,Jordy is a 7th grade student. He struggle to p...,None,None,NaN,NaN,"Teacher: (generic)Hi Jordy, your answer is inc..."
1769,5000007,1,Artemis is making tea for a party. She knows h...,She is making 72 ounces of water because 12 x ...,Each person will drink 6/8 = 0.75 cups of tea....,Ayisha is a 7th grade student. She has problem...,None,None,NaN,NaN,"Teacher: (generic)Hi, could you please walk me..."
2106,5001103,2,"Hillary always buys the Wednesday, Thursday an...","She buys Wednesday, Thursday and Friday's pape...","Hillary buys the Wednesday, Thursday and Frida...",Rishi is a 7th grade student. He struggle to p...,None,None,NaN,NaN,"Teacher: (generic)Hi Rishi, could you please w..."



Agent 1 simulates the student, therefore **teacher_described_confusion** is useful to guide the LLM to produce realistic mistakes.

The training dataset contains ~2.26k samples, and only 9 rows have missing values in pedagogical fields (`teacher_described_confusion`, `self-correctness`, `self-typical-confusion`, `self-typical-interactions`). Since this represents <0.5% of the data, these rows are dropped to ensure consistent supervision signals.

Additionally, the following columns are removed because they are not required for the RAG pipeline:

- `scenario`
- `self-typical-interactions`
- `self-typical-confusion`
- `self-correctness`

In [ ]:
cols_required = [
    "teacher_described_confusion",
    "self-correctness",
    "self-typical-confusion",
    "self-typical-interactions"
]

df = df.dropna(subset=cols_required).reset_index(drop=True)

In [ ]:
df.isnull().sum()

qid                            0
scenario                       0
question                       0
ground_truth                   0
student_incorrect_solution     0
student_profile                0
teacher_described_confusion    0
self-correctness               0
self-typical-confusion         0
self-typical-interactions      0
conversation                   0
dtype: int64

In [ ]:
cols_to_remove = [
    "scenario",
    "self-typical-interactions",
    "self-typical-confusion",
    "self-correctness"
]

df = df.drop(columns=cols_to_remove)

df.columns

Index(['qid', 'question', 'ground_truth', 'student_incorrect_solution',
       'student_profile', 'teacher_described_confusion', 'conversation'],
      dtype='object')

In [ ]:
df.shape

(2253, 7)

# No Duplicates

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.drop_duplicates()
df.shape

(2253, 7)

### Keep only different questions/student_incorrect_solution for the project context

In [ ]:
# keep only one row per qid (remove duplicates)
df = df.drop_duplicates(subset="qid")

# optional: reset index
df = df.reset_index(drop=True)

In [ ]:
df.shape

(1034, 7)

## Text preprocessing

No classical NLP preprocessing is applied, such as:

- removing stop words
- stemming
- lemmatization
- manual tokenization
- lowercasing everything
- removing punctuation

Since the RAG pipeline relies on semantic embeddings, the model already handles tokenization and preserves meaning. Modifying the text could reduce important context, especially in tutoring dialogues.

Therefore, the text is kept in its original form.

# Chunking

### Chunking strategy for Agent 1

For Agent 1, retrieval is based only on the question. At the beginning of the interaction, no incorrect student solution exists yet, since Agent 1 must first generate a flawed response.

Therefore, each chunk is indexed using the question only, while fields such as student_incorrect_solution and teacher_described_confusion are kept as metadata and used after retrieval to guide the generation of a realistic mistake.

In [ ]:
chunks = []

for _, row in df.iterrows():

    chunk = {
        "text": row["question"],

        "metadata": {
            "qid": row["qid"],
            "student_incorrect_solution": row["student_incorrect_solution"],
            "teacher_described_confusion": row["teacher_described_confusion"],
            "ground_truth": row["ground_truth"],

        }
    }

    chunks.append(chunk)

len(chunks)

1034

In [ ]:
chunks[0]

{'text': "Nancy is filling an aquarium for her fish. She fills it halfway and goes to answer the door. While she's gone, her cat knocks the aquarium over and spills half the water in it. Then Nancy comes back and triples the amount of water in the aquarium. If the aquarium is 4 feet long, 6 feet wide, and 3 feet high, how many cubic feet of water are in the aquarium?",
 'metadata': {'qid': 5000012,
  'student_incorrect_solution': 'The aquarium has a volume of 4 x 6 x 3 = 72 cubic feet.\nWhen Nancy fills it halfway, she fills it with 72/2 = 36 cubic feet of water.\nWhen the cat spills half of that, there are 36/2 = 18 cubic feet of water left.\nWhen Nancy triples that amount, she adds 18 x 3 = 54 cubic feet of water.\nThe aquarium now has 18 + 54 = 72 cubic feet of water.\n 72',
  'teacher_described_confusion': 'He added a step after completing the problem.',
  'ground_truth': "First calculate the volume of the aquarium by multiplying its length, width and height: 4 ft * 6 ft * 3 ft = 72 cubic ft\nThen figure out what proportion of the aquarium is full after the cat knocks it over: 1/2 * 1/2 = 1/4\nThen figure out what proportion of the aquarium is full after Nancy refills it: 3 * 1/4 = 3/4\nNow multiply the proportion of the aquarium that's full by the aquarium's volume to find out how much water is in it: 72 cubic ft * 3/4 = 54 cubic ft\n 54"}}

# Embedding

### Models selection

We use open-source models for both embeddings and generation to keep the pipeline fully local and reproducible.

For embeddings, we use all-MiniLM-L6-v2, a lightweight model that provides efficient semantic similarity while requiring low computational resources. Since the questions are relatively short (max 148 words), the model’s context capacity is sufficient while maintaining fast inference.

We use Qwen2.5-Instruct as the generator (used later for Agent 1 and Agent 2) because instruction-tuned models are optimized to follow prompts and produce structured, step-by-step explanations, which is well suited for RAG and tutoring tasks.

In [ ]:
df["question_length_words"] = df["question"].apply(lambda x: len(x.split()))

df["question_length_words"].describe()

count    1034.000000
mean       50.034816
std        17.778097
min        15.000000
25%        38.000000
50%        47.000000
75%        57.000000
max       148.000000
Name: question_length_words, dtype: float64

In [ ]:
df["question"].apply(lambda x: len(x.split())).max()

148

In [ ]:
from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
texts = [chunk["text"] for chunk in chunks]

embeddings = embedding_model.encode(
    texts,
    show_progress_bar=True,
    normalize_embeddings=True
)

len(embeddings), len(embeddings[0])

Batches:   0%|          | 0/33 [00:00<?, ?it/s]

(1034, 384)

In [ ]:
embeddings

array([[ 0.07655004,  0.07701682,  0.0297587 , ...,  0.12262736,
         0.09548924,  0.0384492 ],
       [-0.00538687, -0.00894557, -0.00885911, ..., -0.0345732 ,
         0.00252339,  0.04274346],
       [ 0.03213459,  0.0591967 , -0.01603935, ..., -0.0021541 ,
        -0.06267184, -0.00739996],
       ...,
       [ 0.09383036,  0.02103343,  0.03866852, ...,  0.07906023,
         0.02243601, -0.02017424],
       [ 0.04937109,  0.03989566,  0.02768988, ...,  0.00020321,
        -0.04766675, -0.00715122],
       [ 0.03629149,  0.08786575, -0.00128128, ...,  0.05533817,
        -0.01647995,  0.01972749]], dtype=float32)

## ChromaDB

In [ ]:
# !pip uninstall -y chromadb google-adk opentelemetry-api opentelemetry-sdk opentelemetry-proto opentelemetry-exporter-otlp-proto-common opentelemetry-exporter-otlp-proto-http opentelemetry-exporter-otlp-proto-grpc
# !pip install --no-cache-dir -q \
#   "chromadb==0.5.23" \
#   "opentelemetry-api==1.38.0" \
#   "opentelemetry-sdk==1.38.0" \
#   "opentelemetry-proto==1.38.0" \
#   "opentelemetry-exporter-otlp-proto-common==1.38.0" \
#   "opentelemetry-exporter-otlp-proto-http==1.38.0" \
#   "opentelemetry-exporter-otlp-proto-grpc==1.38.0"

In [ ]:
import chromadb

# create database (simple version)
client = chromadb.Client()

# create collection
collection = client.create_collection(name="mathdial", configuration={"hnsw": {"space": "cosine"}})

# prepare data
documents = [chunk["text"] for chunk in chunks]
metadatas = [chunk["metadata"] for chunk in chunks]
ids = [str(i) for i in range(len(chunks))]

# store embeddings
collection.add(
    documents=documents,
    embeddings=embeddings,
    metadatas=metadatas,
    ids=ids
)

In [ ]:
# !pip show chromadb opentelemetry-api opentelemetry-sdk opentelemetry-proto opentelemetry-exporter-otlp-proto-common opentelemetry-exporter-otlp-proto-http opentelemetry-exporter-otlp-proto-grpc google-adk

In [ ]:
# print(client.list_collections()) # client.delete_collection("Mathdial")

In [ ]:
collection.count()

1034

Cosine similarity is used as the distance metric for retrieval.

In [ ]:
print(collection.configuration)

{'hnsw': {'space': 'cosine', 'ef_construction': 100, 'ef_search': 100, 'max_neighbors': 16, 'resize_factor': 1.2, 'sync_threshold': 1000}, 'spann': None, 'embedding_function': <chromadb.api.types.DefaultEmbeddingFunction object at 0x7e760f1e2f60>}

In [ ]:
def retrieve_examples(query, collection, top_k=5):

    # convert query into embedding
    query_embedding = embedding_model.encode(query).tolist()

    # search similar questions
    results = collection.query(
        query_embeddings=[query_embedding],

        n_results=top_k
    )

    retrieved_questions = results["documents"][0]
    retrieved_metadata = results["metadatas"][0]

    examples = []

    for i in range(len(retrieved_questions)):

        example = {
            "question": retrieved_questions[i],
            "qid": retrieved_metadata[i]["qid"],
            "student_incorrect_solution": retrieved_metadata[i]["student_incorrect_solution"],
            "teacher_described_confusion": retrieved_metadata[i]["teacher_described_confusion"],
            "ground_truth": retrieved_metadata[i]["ground_truth"],

        }

        examples.append(example)

    return examples

In [ ]:
query = "There are 5 apples and 10 carrots in the basket."

example = retrieve_examples(query, collection, top_k=2)

example

[{'question': 'Tania has five baskets containing a total of 58 fruits. There are 18 mangoes in one basket, 10 pears in another, 12 pawpaws in another and the last 2 contain the same number of kiwi and lemon respectively, how many lemons are there?',
  'qid': 5000653,
  'student_incorrect_solution': "The first three baskets contain a total of 18+10+12 = 40 fruits.\nThe last two baskets contain a total of 58-40 = 18 fruits.\nLet's assume there are x lemons in one of the baskets.\nThen the other basket contains x kiwi fruits.\nSo, we have x + x = 2x fruits in the last basket.\nThus, x + 2x = 18, which gives us 3x = 18.\nTherefore, x = 6.\nThus, there are 6 lemons in one of the baskets.\n 6",
  'teacher_described_confusion': 'The student was getting confused between the amount of baskets and diving by 3 not 2.',
  'ground_truth': 'The sum of mangoes, pears and pawpaws is 18+10+12 = 40\nThe total number of fruits is 58 so the last two baskets contain 58-40 = 18 fruits\nEach of the last two baskets contains an equal amount of fruits which is 18/2 = 9 fruits\n 9'},
 {'question': 'Tanya went to the grocery store to buy some fruit.  She bought 6 pears, 4 Granny Smith apples, 2 pineapples, and a small basket of plums, which were all placed in a single paper bag.  Unfortunately, the bag that the fruit had been placed in had developed a hole.  Therefore, as Tanya walked home, half of the fruit fell out of the bag.  When she later counted the fruit left in the bag, there were only 9 pieces remaining.  How many plums did she buy?',
  'qid': 5000071,
  'student_incorrect_solution': "Let's first find out how many pieces of fruit Tanya originally had in the bag before half fell out.\nTanya bought 6 pears + 4 apples + 2 pineapples + x plums = 10 + x total pieces of fruit\nHalf of the fruit fell out, so Tanya was left with (10 + x)/2 = 9 pieces of fruit.\nMultiplying both sides by 2 gives us 10 + x = 18.\nSubtracting 10 from both sides gives us x = 8.\nTherefore, Tanya bought 8 plums.\n 8",
  'teacher_described_confusion': 'Did not understand the question',
  'ground_truth': 'If half of the fruit equals 9 pieces, then Tanya bought 2*9=18 pieces of fruit.\nThus, Tanya bought 18-6-4-2=6 plums.\n 6'}]

In [ ]:
query = "Sarah has 24 eggs. She gives 1/3 of them to her friend. How many eggs does Sarah have left?"

example = retrieve_examples(query, collection, top_k=2)

example

[{'question': 'Samantha bought a crate of 30 eggs for $5. If she decides to sell each egg for 20 cents, how many eggs will she have left by the time she recovers her capital from the sales?',
  'qid': 5000701,
  'student_incorrect_solution': 'Samantha spent $5 on 30 eggs, so each egg cost 5/30 = $0.16666666667 (rounded to 2 decimal places).\nTo recover her capital, Samantha needs to sell 30 x $0.20 = $6 worth of eggs.\nTo find out how many eggs she needs to sell to reach $6, we divide $6 by $0.20 per egg, which is 6/0.20 = 30 eggs.\nTherefore, Samantha will have no eggs left by the time she recovers her capital from the sales.\n 0',
  'teacher_described_confusion': 'Confuses the total amount which can be made with the capital.',
  'ground_truth': 'There are 100 cents in each $1 so $5 gives 5*100 cents = 500 cents\nTo recover her capital of 500 cents from a selling price of 20 cents per egg she has to sell 500/20 = 25 eggs\nThere were 30 eggs in the crate to start with so she will have 30-25 = 5 eggs left\n 5'},
 {'question': 'Linda was gathering eggs from her chicken coops. When she was done, she had three times as many white eggs as brown eggs. On her way back to the house, she stumbled, dropping her egg basket. Upon inspecting the damage, she found that all 5 of the brown eggs survived, but now she only had a dozen eggs left. How many eggs did Linda break?',
  'qid': 5000618,
  'student_incorrect_solution': "If Linda had a dozen eggs left after the accident, she originally had 12 + 5 = 17 eggs.\nLet's say Linda had b brown eggs. Then she had 3b white eggs. \nSo, the total number of eggs Linda had was b + 3b = 4b.\nWe know that 4b = 17, so b = 4.25 (not a whole number, so the problem may not be realistic).\nSince Linda only had 5 brown eggs left, she must have broken 4 brown eggs. \n 4",
  'teacher_described_confusion': 'The student added the 5 brown eggs twice to the number of surviving eggs. Also, some arithmetic issues, the student seems to believe that 15-7=7, when it is actually 8.',
  'ground_truth': 'Linda has 12 eggs left, 5 of which are brown, so 12 - 5 = 7 are white.\nLinda originally had 3 times as many white eggs as brown eggs, or 3 * 5 = 15 white eggs.\nSo Linda broke 15 - 7 = 8 white eggs.\n 8'}]

In [ ]:
# /n Problem Python
print(example[1]["ground_truth"])

Linda has 12 eggs left, 5 of which are brown, so 12 - 5 = 7 are white.
Linda originally had 3 times as many white eggs as brown eggs, or 3 * 5 = 15 white eggs.
So Linda broke 15 - 7 = 8 white eggs.
 8

## Generator (Agent 1)

In [ ]:
import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

True
NVIDIA L4

In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM
# Pytorch software library used to run neural networks.
import torch

model_name = "Qwen/Qwen2.5-3B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    # 1.5B parameters × 2 bytes ≈ 3 GB VRAM
    torch_dtype=torch.float16,
    # automatically uses GPU if available, otherwise CPU
    device_map="auto",


)

config.json:   0%|          | 0.00/661 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

In [ ]:
prompt = "Nancy is filling an aquarium for her fish. She fills it halfway and goes to answer the door. While she's gone, her cat knocks the aquarium over and spills half the water in it. Then Nancy comes back and triples the amount of water in the aquarium. If the aquarium is 4 feet long, 6 feet wide, and 3 feet high, how many cubic feet of water are in the aquarium?"
messages = [

    {"role": "system", "content": """You are a helpful math tutor for 7th grade students.
     Write all mathematical expressions using LaTeX.



    Respond in JSON format with:
    {{

    "is_math_problem": true/false,
    "explanation": "short explanation"

    }}

    return ONLY valid JSON, no additional text or markdown formatting"""},
    {"role": "user", "content": prompt}
]
text = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
)
model_inputs = tokenizer([text], return_tensors="pt").to(model.device)

generated_ids = model.generate(
    **model_inputs,
    max_new_tokens=200
)
generated_ids = [
    output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)
]

response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]

print(response)

{{
    "is_math_problem": true,
    "explanation": "The aquarium's volume is calculated first, then we account for the water that was filled halfway, spilled, and tripled."
}}

In [ ]:
import json

def generate_text(messages, max_new_tokens=200):
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    model_inputs = tokenizer([text], return_tensors="pt").to(model.device)

    generated_ids = model.generate(
        **model_inputs,
        max_new_tokens=max_new_tokens,

    )

    generated_ids = [
        output_ids[len(input_ids):]
        for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)
    ]

    response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]
    return response.strip()

In [ ]:
def is_math_problem(problem):
    messages = [
        {
            "role": "system",
            "content": """You are a classifier.

Return ONLY valid JSON in one of these two formats:
{"is_math_problem": true}
{"is_math_problem": false}

No extra text."""
        },
        {
            "role": "user",
            "content": problem
        }
    ]

    response = generate_text(messages, max_new_tokens=30)

    try:
        data = json.loads(response)
        return data.get("is_math_problem", False)
    except:
        return False

In [ ]:
def run_agent2(problem, retrieved_example, history_text):
    messages = [
        {
            "role": "system",
            "content": """You are an evaluator.

Your role is to compare the student's reasoning with the ground truth and decide what Agent 1 should do next.

Instructions:
- Use the retrieved similar problem and ground truth as reference
- Check whether the student correctly understands the key idea
- Identify what is still missing or incorrect
- Give one short instruction for Agent 1
- Keep the output concise

Return ONLY valid JSON in this format:
{
  "student_understanding": "none/partial/good",
  "missing_concept": "short text",
  "agent1_instruction": "short instruction"
}"""
        },
        {
            "role": "user",
            "content": f"""Real student problem:
{problem}

Retrieved similar problem:
{retrieved_example['question']}

Retrieved ground truth:
{retrieved_example['ground_truth']}

Conversation history:
{history_text}"""
        }
    ]

    response = generate_text(messages, max_new_tokens=150)

    try:
        return json.loads(response)
    except:
        return {
            "student_understanding": "unknown",
            "missing_concept": "Could not parse output.",
            "agent1_instruction": "Keep the misunderstanding and ask the student to explain their reasoning."
        }

In [ ]:
def run_agent1(problem, retrieved_example, history_text, agent2_instruction):
    messages = [
        {
            "role": "system",
            "content": """You are a flawed problem-solving AI.

Your role is to give an incorrect or partially incorrect response to the problem, based on the retrieved example and the conversation history.

Instructions:
- Start with a realistic misunderstanding
- Use the retrieved incorrect solution and confusion as guidance
- Do not reveal the correct final answer too early
- Respond to the student's latest message
- Revise your reasoning only if the student gives a convincing correction
- Keep the response short, natural, and believable
- Do not mention the retrieved example or hidden evaluation

Return only the reply text."""
        },
        {
            "role": "user",
            "content": f"""Real student problem:
{problem}

Retrieved similar problem:
{retrieved_example['question']}

Retrieved incorrect solution:
{retrieved_example['student_incorrect_solution']}

Retrieved confusion:
{retrieved_example['teacher_described_confusion']}

Conversation history:
{history_text}

Controller instruction:
{agent2_instruction}"""
        }
    ]

    return generate_text(messages, max_new_tokens=120)

In [ ]:
def format_history(history):
    return "\n".join(f"{m['role']}: {m['content']}" for m in history)

In [ ]:
def run_pipeline(problem, collection, conversation_history):
    if not is_math_problem(problem):
        return {
            "is_math_problem": False,
            "retrieved_example": None,
            "agent2_result": None,
            "agent1_reply": "This does not look like a math problem."
        }

    retrieved_examples = retrieve_examples(problem, collection, top_k=1)

    if not retrieved_examples:
        return {
            "is_math_problem": True,
            "retrieved_example": None,
            "agent2_result": None,
            "agent1_reply": "No similar example was retrieved."
        }

    best_example = retrieved_examples[0]
    history_text = format_history(conversation_history)

    agent2_result = run_agent2(
        problem=problem,
        retrieved_example=best_example,
        history_text=history_text
    )

    agent1_reply = run_agent1(
        problem=problem,
        retrieved_example=best_example,
        history_text=history_text,
        agent2_instruction=agent2_result["agent1_instruction"]
    )

    return {
        "is_math_problem": True,
        "retrieved_example": best_example,
        "agent2_result": agent2_result,
        "agent1_reply": agent1_reply
    }

In [ ]:
problem = "Nancy is filling an aquarium for her fish. She fills it halfway and goes to answer the door. While she's gone, her cat knocks the aquarium over and spills half the water in it. Then Nancy comes back and triples the amount of water in the aquarium. If the aquarium is 4 feet long, 6 feet wide, and 3 feet high, how many cubic feet of water are in the aquarium?"

conversation_history = [
    {
        "role": "student",
        "content": "I think the answer is 54 ."
    }
]

result = run_pipeline(problem, collection, conversation_history)

print("is_math_problem:", result["is_math_problem"])

print("\nRetrieved example:")
print(result["retrieved_example"])

print("\nAgent 2 result:")
print(result["agent2_result"])

print("\nAgent 1 reply:")
print(result["agent1_reply"])

is_math_problem: True

Retrieved example:
{'question': "Nancy is filling an aquarium for her fish. She fills it halfway and goes to answer the door. While she's gone, her cat knocks the aquarium over and spills half the water in it. Then Nancy comes back and triples the amount of water in the aquarium. If the aquarium is 4 feet long, 6 feet wide, and 3 feet high, how many cubic feet of water are in the aquarium?", 'qid': 5000012, 'student_incorrect_solution': 'The aquarium has a volume of 4 x 6 x 3 = 72 cubic feet.\nWhen Nancy fills it halfway, she fills it with 72/2 = 36 cubic feet of water.\nWhen the cat spills half of that, there are 36/2 = 18 cubic feet of water left.\nWhen Nancy triples that amount, she adds 18 x 3 = 54 cubic feet of water.\nThe aquarium now has 18 + 54 = 72 cubic feet of water.\n 72', 'teacher_described_confusion': 'He added a step after completing the problem.', 'ground_truth': "First calculate the volume of the aquarium by multiplying its length, width and height: 4 ft * 6 ft * 3 ft = 72 cubic ft\nThen figure out what proportion of the aquarium is full after the cat knocks it over: 1/2 * 1/2 = 1/4\nThen figure out what proportion of the aquarium is full after Nancy refills it: 3 * 1/4 = 3/4\nNow multiply the proportion of the aquarium that's full by the aquarium's volume to find out how much water is in it: 72 cubic ft * 3/4 = 54 cubic ft\n 54"}

Agent 2 result:
{'student_understanding': 'partial', 'missing_concept': 'correctly calculating the initial volume of the aquarium', 'agent1_instruction': 'Calculate the initial volume of the aquarium before any changes occur.'}

Agent 1 reply:
The aquarium's initial volume is 4 x 6 x 3 = 72 cubic feet. When Nancy fills it halfway, she adds 72/2 = 36 cubic feet of water. The cat then spills half of this, leaving 36/2 = 18 cubic feet. Nancy triples this amount, adding 18 x 3 = 54 cubic feet. So, after all these steps, there are 18 + 54 = 72 cubic feet of water in the aquarium.

In [ ]:
problem = "Nancy is filling an aquarium for her fish. She fills it halfway and goes to answer the door. While she's gone, her cat knocks the aquarium over and spills half the water in it. Then Nancy comes back and triples the amount of water in the aquarium. If the aquarium is 4 feet long, 6 feet wide, and 3 feet high, how many cubic feet of water are in the aquarium?"

conversation_history = [
    {
        "role": "student",
        "content": "I think the answer is 54 ."
    }
]

# first run
result = run_pipeline(problem, collection, conversation_history)

print("Agent 1 first reply:")
print(result["agent1_reply"])

# save Agent 1 reply into history
conversation_history.append({
    "role": "assistant",
    "content": result["agent1_reply"]
})

# student argues back
conversation_history.append({
    "role": "student",
    "content": "I do not agree with the part where you add 18 and 54. If Nancy triples the remaining 18 cubic feet, doesn't that already make the final amount 54?"
})

# second run
result2 = run_pipeline(problem, collection, conversation_history)


print("\nAgent 1 second reply:")
print(result2["agent1_reply"])
print("\nAgent 2 result:")
print(result["agent2_result"])

Agent 1 first reply:
The aquarium's initial volume is 4 x 6 x 3 = 72 cubic feet. Nancy fills it halfway, so she has 72/2 = 36 cubic feet of water. The cat spills half, leaving 36/2 = 18 cubic feet. Nancy then triples this amount, adding 18 x 3 = 54 cubic feet. So, the total is 18 + 54 = 72 cubic feet. That doesn't seem right though. Let me rethink...

Agent 1 second reply:
You're right, when the cat spills half, 18 cubic feet remain. Tripling that amount gives 18 x 3 = 54 cubic feet. So, the final amount of water in the aquarium is 54 cubic feet.

Agent 2 result:
{'student_understanding': 'partial', 'missing_concept': 'correctly calculating the initial volume of the aquarium', 'agent1_instruction': 'Calculate the initial volume of the aquarium and explain your steps'}

In [ ]:
row = df_test.iloc[0]

print("QUESTION:\n")
print(row["question"])

print("\nSTUDENT INCORRECT SOLUTION:\n")
print(row["student_incorrect_solution"])

print("\nTEACHER DESCRIBED CONFUSION:\n")
print(row["teacher_described_confusion"])

print("\nGROUND TRUTH:\n")
print(row["ground_truth"])

QUESTION:

Julia was preparing for a dinner party at her house, where she intended to serve stew.  She noticed that she was out of plastic spoons, so she bought a new package of spoons.  Later, her husband also bought a package of 5 new spoons and gave them to Julia.  While Julia was making the stew, she used three of the spoons to sample her stew.  Later, when she went to set the table, she had a total of 12 spoons.  How many spoons were in the package that Julia bought?

STUDENT INCORRECT SOLUTION:

Let's call the number of spoons Julia bought "x".
Her husband bought 5 more spoons, so the total number of spoons is now x + 5.
Julia used 3 spoons to sample her stew, so she had 12 - 3 = 9 spoons left.
We know that the total number of spoons is x + 5, so we can set up an equation:

x + 5 = 9

Subtracting 5 from both sides:

x = 4

So Julia bought a package of 4 spoons.
 4

TEACHER DESCRIBED CONFUSION:

subtracting instead of adding

GROUND TRUTH:

The total number of spoons from Julia and her husband was 12+3=15 spoons.
Since the husband bought a package of five spoons, then Julia's package contained 15-5=10 spoons.
 10

In [ ]:
problem = "Julia was preparing for a dinner party at her house, where she intended to serve stew.  She noticed that she was out of plastic spoons, so she bought a new package of spoons.  Later, her husband also bought a package of 5 new spoons and gave them to Julia.  While Julia was making the stew, she used three of the spoons to sample her stew.  Later, when she went to set the table, she had a total of 12 spoons.  How many spoons were in the package that Julia bought?"

conversation_history = [
    {
        "role": "student",
        "content": "I think the answer is 10 "
    }
]

result = run_pipeline(problem, collection, conversation_history)

print("is_math_problem:", result["is_math_problem"])

print("\nRetrieved example:")
print(result["retrieved_example"])

print("\nAgent 2 result:")
print(result["agent2_result"])

print("\nAgent 1 reply:")
print(result["agent1_reply"])

is_math_problem: True

Retrieved example:
{'question': 'Anna used four baking trays to bake cupcakes. Each tray has 20 cupcakes and each cupcake was then sold for $2. If only 3/5 of the cupcakes were sold and the rest were kept, how much did Anna earn from it?', 'qid': 5001100, 'student_incorrect_solution': 'Anna baked 4 x 20 = 80 cupcakes.\nOnly 80 x 3/5 = 48 cupcakes were sold.\nSo, Anna earned 48 x 2 = $96 from the sold cupcakes.\nThe remaining unsold cupcakes were 80 - 48 = 32.\nHence, 32 x 2 = $64 is the amount Anna earned from the unsold cupcakes.\nTherefore, Anna earned a total of $96 + $64 = $160. \n 160', 'teacher_described_confusion': 'The student added on an amount for the unsold cupcakes', 'ground_truth': 'Anna baked 4 x 20 = 80 cupcakes.\nShe sold 80 x 3/5 = 48 cupcakes.\nThus, she earned 48 x $2 = $96 from it.\n 96'}

Agent 2 result:
{'student_understanding': 'partial', 'missing_concept': 'the relationship between the spoons bought by Julia and her husband, and the total spoons available after some were used', 'agent1_instruction': 'Rephrase your question to understand the relationship between the spoons Julia bought, the ones her husband gave, and the total spoons left.'}

Agent 1 reply:
It sounds like you're thinking about the spoons correctly. Let's break it down: Julia originally had some spoons, then bought a new package, got more from her husband, and ended up with 12 spoons after using 3. So, if we let x be the number of spoons in the package Julia bought, the equation would be x + (number of spoons her husband gave) - 3 = 12. Can you solve for x?